encoder_dataset:
  - ZINC1k
classifier_dataset:
  - JAK1
# model:
#   - GIN
use_encoder:
   - true
   - false
embedding_dim:
  - 128
  - 256
  - 512
device:
  - cuda:0
batch_size:
  - 32
  # - 128
learning_rate:
  # - 0.01
  - 0.001
  - 0.0001
encoder_epochs:
  - 1
classifier_epochs:
  # - 100
  - 1000
frozen_epochs:
  - 3
hidden_units:  # Note: GIN add a first layer that simply adds up all node features
  - [64, 64, 64, 64]
  - [32, 32, 32, 32]
  # - [64]
  # - [32, 32]
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 20
      gamma: 0.5
encoder_loss:
  - BCELoss
  # - MulticlassClassificationLoss
classifier_loss:
  - NLLLoss
train_eps:
  - true
  # - false
l2:
  - 0.
aggregation:
  - mean
  # - sum
gradient_clipping:
  - null
dropout:
  - 0.5
  # - 0.
early_stopper:
#   # -
#   #   class: Patience
#   #   args:
#   #     patience: 500
#   #     use_loss: False
  -
    class: Patience
    args:
      patience: 20
      use_loss: True
shuffle:
  - True
resume:
  - False